apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secrets
  namespace: collaborative-truck-scheduling
spec:
  type: secretstores.local.file
  version: v1  
  metadata:
  - name: secretsFile
    value: ../dapr/components/secrets.json
  - name: nestedSeparator
    value: "."
scopes:
  - collaborativetruckschedulingservice