apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: store-topological-map
  namespace: collaborative-truck-scheduling
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    secretKeyRef:
      name: state.redisPassword
      key: state.redisPassword
  - name: actorStateStore
    value: "true"
auth:
  secretStore: itos-secrets
scopes:
  - collaborativetruckschedulingservice